---

- name: install package python-configobj
  package: 
    name: python-configobj
    state: present

- name: install package python-cheetah
  package: 
    name: python-cheetah
    state: present

- name: install package python-imaging
  package: 
    name: python-imaging
    state: present

- name: install package python-serial
  package: 
    name: python-serial
    state: present

- name: install package python-usb
  package: 
    name: python-usb
    state: present

- name: install package mysql-client
  package: 
    name: mysql-client
    state: present

- name: install package python-mysqldb
  package: 
    name: python-mysqldb
    state: present

- name: install package ftp
  package: 
    name: ftp
    state: present

- name: install package python-dev
  package: 
    name: python-dev
    state: present

- name: install package python-pip
  package: 
    name: python-pip
    state: present

- name: install pip package pyephem
  pip:
    name: pyephem

