---

- name: add weewx user
  user:
    name: weewx
    shell: /bin/bash
    state: present

- name: download weewx binary
  get_url:
    url: http://weewx.com/downloads/weewx-3.7.1.tar.gz
    dest: /opt
    mode: 0777

- name: expand archive
  unarchive:
    src: /opt/weewx-3.7.1.tar.gz
    dest: /opt
    remote_src: True

- name: build weewx binaries
  command: ./setup.py build
  args:
    chdir: /opt/weewx-3.7.1

# not working yet
#- name: install weewx binaries
#  command: ./setup.py install
#  args:
#    chdir: /opt/weewx-3.7.1

