---

- name: add weewx user
  user:
    name: weewx
    shell: /bin/bash
    state: present

- name: install package python-configobj
  package: 
    name: python-configobj
    state: present

- name: install package python-cheetah
  package: 
    name: python-cheetah
    state: present

- name: install package python-imaging
  package: 
    name: python-imaging
    state: present

- name: install package python-serial
  package: 
    name: python-serial
    state: present

- name: install package python-usb
  package: 
    name: python-usb
    state: present

- name: install package mysql-client
  package: 
    name: mysql-client
    state: present

- name: install package python-mysqldb
  package: 
    name: python-mysqldb
    state: present

- name: install package ftp
  package: 
    name: ftp
    state: present

- name: install package python-dev
  package: 
    name: python-dev
    state: present

- name: install package python-pip
  package: 
    name: python-pip
    state: present

- name: install pip package pyephem
  pip:
    name: pyephem

- name: download weewx binary
  get_url:
    url: http://weewx.com/downloads/weewx-3.7.1.tar.gz
    dest: /opt
    mode: 0777

- name: expand archive
  unarchive:
    src: /opt/weewx-3.7.1.tar.gz
    dest: /opt
    remote_src: True

- name: build weewx binaries
  command: ./setup.py build
  args:
    chdir: /opt/weewx-3.7.1

# not working yet
#- name: install weewx binaries
#  command: ./setup.py install
#  args:
#    chdir: /opt/weewx-3.7.1

